# 𝘼𝙒𝙖𝙩𝙘𝙝𝘽𝙤𝙤𝙨𝙩𝙚𝙧 模块配置文件
# 如果配置错误模块会使用默认配置
# 会自动输出模块日志到 config.yaml.log
# 修改完之后记得重启喔

# [🚀性能调节]

# 选择 CPU 性能模式（默认: 0）
# 0: 性能优先
# 1: 省电优先（使用此项会忽略下方核心分配，使用模块的省电预设）
性能模式 0

# 用户后台应用（推荐: 0-1）
用户后台应用 0-1
# 系统后台应用（推荐: 0）
系统后台应用 0
# 前台应用（推荐: 0-3）
前台应用 0-3
# 上层应用（悬浮窗）（推荐: 0-3）
上层应用 0-3

# [✨额外选项]

# TCP 网络优化（默认: 0）
# 0: 开启网络优化
# 1: 关闭网络优化
TCP网络优化 0

# 禁用模块日志输出（默认: 0）
# 0: 输出默认日志
# 1: 禁用日志功能
模块日志输出 0

# 开启无线 ADB 调试（默认: 0 端口: 5555）
# 0: 开启
# 1: 关闭
无线ADB调试 0

# 是否启用 ZRAM（默认: 0)
# ZRAM 通过在 RAM 内的压缩块设备的分页来“创造”更多内存空间
# 但是它在使用时会占用大量 CPU 资源，可能会加剧耗电
# 如果你的内存充足（4G 或 3G RAM）的型号，则不建议开启
# 0: 关闭
# 1: 开启
ZRAM状态 0

# 是否解除安装限制（默认: 0)
# 0: 解除
# 1: 不解除
# 已测试机型：CD100
安装限制状态 0