# 𝘼𝙒𝙖𝙩𝙘𝙝𝘽𝙤𝙤𝙨𝙩𝙚𝙧 模块配置文件
# 模块 GitHub 仓库地址: https://github.com/No-22-Github/Magisk_AWatchBooster
# 模块下载地址 (GitHub): https://github.com/No-22-Github/Magisk_AWatchBooster/releases

# QQ反馈&交流群：824923954

# 🔧 配置文件使用说明：
# 格式： 配置项_选项
# 例如：配置项1_0 即为选择0选项

# [🚀 性能调节]

# 📉 控制 CPU 频率最高值
# ⚠️ 此项为风险操作 不懂勿动 ⚠️
# 可以限制 CPU 频率的最大值，请填入下方获取到的可选值之一
# 例如，填入[1100]即为限制最大频率为1100 Mhz，填入[1]即为禁用
# ⚠️ 请填入获取到的可用值之一 ⚠️
# ⚠️ 在频率限制后填入纯数字即可，如[768]  ⚠️
可用频率档位:

频率限制_1

# 📈 选择 CPU 性能模式（默认: 0）
# 选择设备的 CPU 性能模式，优化设备的运行效率。
# 0: 性能优先 (性能较好，耗电快，适合玩游戏 (?) )
# 1: 均衡模式 (默认) (均衡，一般来说比原厂调度省电)
# 2: 省电优先（此选项将自动忽略下方的核心分配设置，采用模块的省电预设）
性能模式_1

# 🌡️ CPU / GPU 温控调节（默认: 60）
# 设置 CPU 和 GPU 的温控上限。为了延长电池寿命，推荐将温度控制在 60°C 以下
# 此项可能无效
温度控制_60

# 🧠 CPU 核心分配
# 分配 CPU 核心以优化设备的性能和电池寿命。根据应用的使用场景，合理配置后台和前台应用的核心使用。
# 用户后台应用（推荐: 0-1）：限制后台应用的 CPU 核心数。
# 系统后台应用（推荐: 0）：系统后台应用通常无需占用过多核心。
# 前台应用（推荐: 0-3）：前台应用应使用较多核心以提高响应速度。
# 上层应用（悬浮窗）（推荐: 0-3）：悬浮窗应用可使用更多核心以提高多任务处理能力。
用户后台应用_0-1
系统后台应用_0
前台应用_0-3
上层应用_0-3

# [✨ 额外选项]

# 🔒 禁用模块日志输出（默认: 0）
# 选择是否禁用模块日志的输出。如果您不需要日志信息，可以关闭它来节省存储空间。
# 0: 输出默认日志
# 1: 禁用日志功能
模块日志输出_0

# 📱 开启无线 ADB 调试（默认: 0 端口: 5555）
# 无线调试功能可以让您通过无线网络进行 ADB 调试，默认为开启。
# 0: 开启无线调试
# 1: 关闭无线调试
无线ADB调试_0

# 📲 锁定 USB 配置为 MTP 协议 (默认： 1)
# MTP 协议可以使手表能和电脑或其他设备传输文件
# 使用循环检测 USB 协议状态，设置为 MTP 协议
# 0: 启用此功能
# 1: 禁用此功能
设置USB为MTP_1

# 💾 是否启用 ZRAM（默认: 0）
# ZRAM 可以在物理内存中创建压缩的块设备，用于交换内存空间，从而释放更多内存。但是，它会占用 CPU 资源，可能会加剧电池消耗。
# 0: 关闭 ZRAM
# 1: 启用 ZRAM
# ⚠️ 提示：如果您的设备内存大于 3GB（如 4GB 或更多），可以考虑关闭 ZRAM 以避免不必要的资源消耗。
ZRAM状态_0

# [🚧 测试选项]

# 🔋息屏降频省电功能
# 检测到息屏后自动降低 CPU 频率以达到省电目的（默认: 0）
# 0: 开启息屏降频省电
# 1: 关闭息屏降频省电
息屏降频_0
# 以下为逐项解释↓
# 1.渐进增加（ 0为启用，1为禁用 ）即为启用渐进式增加检测周期，连续 5 次都是息屏状态就会开始增加检测周期
# 2.检测周期（ 单位：秒 ）检测屏幕状态的时间间隔
# 3.最大倍率（ 仅在 [渐进增加设置为0] 时启用 ）设置默认检测周期到最高检测周期的倍率
# 举例：四项设置为 [0，5，50] 时设备在息屏后每隔5秒检测一次屏幕状态，25秒后（5*5=25）逐渐增加检测周期，最多到250（5*50=250）秒检测一次
渐进增加_0
检测周期_5
最大倍率_50

# 息屏降频省电·附加
# 💤延迟唤醒
# 检测到亮屏后等待若干秒再检测，如果仍然亮屏，再提高频率
# 适合开启抬腕亮屏的人群
# 0: 开启延迟唤醒
# 1: 关闭延迟唤醒
# 延迟时间填入抬腕亮屏后自动息屏所需的时间即可 (单位: 秒)
延迟唤醒_1
延迟时间_5

# [🛠️ Debug选项]

# 在控制台打印日志，没事别动，默认[1]关闭
开启Debug输出_1

# ⚠️ 注意事项：
# - 修改完配置文件后，务必重启设备使更改生效。
# - 配置错误时，模块将自动使用默认配置或禁用此功能。