# 𝘼𝙒𝙖𝙩𝙘𝙝𝘽𝙤𝙤𝙨𝙩𝙚𝙧 模块配置文件
# 模块 GitHub 仓库地址: https://github.com/No-22-Github/Magisk_AWatchBooster
# 模块下载地址 (GitHub): https://github.com/No-22-Github/Magisk_AWatchBooster/releases
# 模块下载地址 (Houlangs国内镜像): https://service.houlangs.cn/AWatchBooster/download
# [🚀 性能调节]

# 📈 选择 CPU 性能模式（默认: 0）
# 选择设备的 CPU 性能模式，优化设备的运行效率。
# 0: 性能优先
# 1: 省电优先（此选项将自动忽略下方的核心分配设置，采用模块的省电预设）
性能模式_0

# 🌡️ CPU / GPU 温控调节（默认: 60）
# 设置 CPU 和 GPU 的温控上限。为了延长电池寿命，推荐将温度控制在 60°C 以下。
温度控制_60

# 🧠 CPU 核心分配
# 分配 CPU 核心以优化设备的性能和电池寿命。根据应用的使用场景，合理配置后台和前台应用的核心使用。
# 用户后台应用（推荐: 0-1）：限制后台应用的 CPU 核心数。
# 系统后台应用（推荐: 0）：系统后台应用通常无需占用过多核心。
# 前台应用（推荐: 0-3）：前台应用应使用较多核心以提高响应速度。
# 上层应用（悬浮窗）（推荐: 0-3）：悬浮窗应用可使用更多核心以提高多任务处理能力。
用户后台应用_0-1
系统后台应用_0
前台应用_0-3
上层应用_0-3

# [✨ 额外选项]

# 🌐 TCP 网络优化（默认: 0）
# 启用或禁用网络优化，优化网络连接以提高上网速度。
# 0: 开启网络优化
# 1: 关闭网络优化
TCP网络优化_0

# 🔒 禁用模块日志输出（默认: 0）
# 选择是否禁用模块日志的输出。如果您不需要日志信息，可以关闭它来节省存储空间。
# 0: 输出默认日志
# 1: 禁用日志功能
模块日志输出_0

# 📱 开启无线 ADB 调试（默认: 0 端口: 5555）
# 无线调试功能可以让您通过无线网络进行 ADB 调试，默认为开启。
# 0: 开启无线调试
# 1: 关闭无线调试
无线ADB调试_0

# 💾 是否启用 ZRAM（默认: 0）
# ZRAM 可以在物理内存中创建压缩的块设备，用于交换内存空间，从而释放更多内存。但是，它会占用 CPU 资源，可能会加剧电池消耗。
# 0: 关闭 ZRAM
# 1: 启用 ZRAM
# ⚠️ 提示：如果您的设备内存大于 3GB（如 4GB 或更多），可以考虑关闭 ZRAM 以避免不必要的资源消耗。
ZRAM状态_0

# 🚫 是否解除安装限制（默认: 0）
# 解除安装限制让您能够安装一些可能被系统或应用商店限制的 APK 文件。
# 0: 解除安装限制
# 1: 不解除安装限制
# 已测试机型：CD100
安装限制状态_0

# ⚠️ 注意事项：
# - 修改完配置文件后，务必重启设备使更改生效。
# - 配置错误时，模块将自动使用默认配置。